AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestFunction:
    Properties:
      CodeUri: s3://graphqlservertest/3fe98f8f637e110bb321c76fe14e1bcb
      Events:
        GetRequest:
          Properties:
            Method: get
            Path: /graphql
          Type: Api
        PostRequest:
          Properties:
            Method: post
            Path: /graphql
          Type: Api
      Handler: graphql.handler
      Runtime: nodejs4.3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
