AWSTemplateFormatVersion: '2010-09-09'
Resources:
  GraphQL:
    Properties:
      CodeUri: s3://graphqlservertest2/58801ee57ac21e032eeafd2c1f50946c
      Events:
        GetRequest:
          Properties:
            Method: get
            Path: /graphql
          Type: Api
        PostRequest:
          Properties:
            Method: post
            Path: /graphql
          Type: Api
      Handler: graphql.graphqlHandler
      Runtime: nodejs4.3
    Type: AWS::Serverless::Function
  GraphQLInspector:
    Properties:
      CodeUri: s3://graphqlservertest2/58801ee57ac21e032eeafd2c1f50946c
      Events:
        GetRequest:
          Properties:
            Method: get
            Path: /graphiql
          Type: Api
      Handler: graphql.graphiqlHandler
      Runtime: nodejs4.3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
